# Generated by Django 4.2.6 on 2023-10-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gamevocab",
            fields=[
                (
                    "game_vocab_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("game_vocab", models.CharField(max_length=100)),
                ("game_stage", models.BigIntegerField()),
                ("language_id", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "GameVocab",
                "managed": False,
            },
        ),
    ]
